spring:
  application:
    name: online-learning-server
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    baseline-on-migrate: true
    baseline-version: 0

