application:
  security:
    jwt:
      secret-key: 1234123412341234123412341234123412341234123412341234123412341234
      access-token-expiration-ms: 3600000
      refresh-token-expiration-ms: 604800000

spring:
  application:
    name: online-learning-server
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    baseline-on-migrate: true
    baseline-version: 0

