CREATE TABLE answer_options
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text         VARCHAR(500)                            NOT NULL,
    is_correct   BOOLEAN                                 NOT NULL,
    option_order INTEGER,
    question_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_answer_options PRIMARY KEY (id)
);

CREATE TABLE educational_materials
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title                VARCHAR(255)                            NOT NULL,
    topic                VARCHAR(100)                            NOT NULL,
    reading_time_minutes INTEGER,
    author_id            BIGINT                                  NOT NULL,
    created_at           TIMESTAMP with time zone                NOT NULL,
    updated_at           TIMESTAMP with time zone                NOT NULL,
    CONSTRAINT pk_educational_materials PRIMARY KEY (id)
);

CREATE TABLE questions
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text           TEXT                                    NOT NULL,
    question_order INTEGER,
    test_id        BIGINT                                  NOT NULL,
    CONSTRAINT pk_questions PRIMARY KEY (id)
);

CREATE TABLE refresh_tokens
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    token       VARCHAR(512)                            NOT NULL,
    expiry_date TIMESTAMP with time zone                NOT NULL,
    revoked     BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id)
);

CREATE TABLE tests
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title                   VARCHAR(255),
    educational_material_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_tests PRIMARY KEY (id)
);

CREATE TABLE text_blocks
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title                   VARCHAR(255),
    content                 TEXT                                    NOT NULL,
    block_order             INTEGER,
    educational_material_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_text_blocks PRIMARY KEY (id)
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username   VARCHAR(50)                             NOT NULL,
    email      VARCHAR(100)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    role       VARCHAR(20)                             NOT NULL,
    created_at TIMESTAMP with time zone                NOT NULL,
    updated_at TIMESTAMP with time zone                NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE refresh_tokens
    ADD CONSTRAINT UC_REFRESH_TOKENS_TOKEN UNIQUE (token);

ALTER TABLE tests
    ADD CONSTRAINT UC_TESTS_EDUCATIONAL_MATERIAL UNIQUE (educational_material_id);

ALTER TABLE users
    ADD CONSTRAINT UC_USERS_EMAIL UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT UC_USERS_USERNAME UNIQUE (username);

ALTER TABLE answer_options
    ADD CONSTRAINT FK_ANSWER_OPTIONS_ON_QUESTION FOREIGN KEY (question_id) REFERENCES questions (id);

ALTER TABLE educational_materials
    ADD CONSTRAINT FK_EDUCATIONAL_MATERIALS_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES users (id);

ALTER TABLE questions
    ADD CONSTRAINT FK_QUESTIONS_ON_TEST FOREIGN KEY (test_id) REFERENCES tests (id);

ALTER TABLE refresh_tokens
    ADD CONSTRAINT FK_REFRESH_TOKENS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE tests
    ADD CONSTRAINT FK_TESTS_ON_EDUCATIONAL_MATERIAL FOREIGN KEY (educational_material_id) REFERENCES educational_materials (id);

ALTER TABLE text_blocks
    ADD CONSTRAINT FK_TEXT_BLOCKS_ON_EDUCATIONAL_MATERIAL FOREIGN KEY (educational_material_id) REFERENCES educational_materials (id);